### ISSUE TITLE
Which perl packages are required?

### ISSUE THREAD

**Issue by xyproto** [tfheen/trafikanten-cli#1]
Hi :)

When running "trafikanten", I get:

Can't locate Config/File.pm in @INC (@INC contains: /usr/lib/perl5/site_perl /usr/share/perl5/site_perl /usr/lib/perl5/vendor_perl /usr/share/perl5/vendor_perl /usr/lib/perl5/core_perl /usr/share/perl5/core_perl .) at ./trafikanten line 36.
BEGIN failed--compilation aborted at ./trafikanten line 36.

Which perl packages are required? I tried quite a few of the packages named something with "perl" and "configure" that are available for Arch Linux.

I'm on 64-bit Arch Linux, using perl 5, version 14, subversion 1 (v5.14.1) built for x86_64-linux-thread-multi.

Sincerely,
Alexander Rødseth

**Comment by tfheen** [comment]
libconfig-file-perl is the Debian package name.  I don't know how Arch names their perl packages, though.

**Comment by xyproto** [comment]
After packaging libconfig-file-perl, trafikanten-cli now runs.
